name: app_pintor
description: "App para orçamentos e gestão de serviços de pintura."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# ----------------------------------------------------------------------
# DEPENDÊNCIAS DO APP (Pacotes necessários para o aplicativo funcionar)
# ----------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2      # Gerenciamento de estado
  hive: ^2.2.3          # Banco de dados local super rápido
  hive_flutter: ^1.1.0  # Integração do banco com o Flutter
  path_provider: ^2.1.1 # Acessar pastas do celular
  pdf: ^3.10.4          # Geração do arquivo PDF
  printing: ^5.11.0     # Visualizar e imprimir o PDF
  url_launcher: ^6.2.6  # Para abrir o WhatsApp e outras URLs
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

# ----------------------------------------------------------------------
# DEPENDÊNCIAS DE DESENVOLVIMENTO (Ferramentas para quem está programando)
# ----------------------------------------------------------------------
dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# ----------------------------------------------------------------------
# CONFIGURAÇÕES DO FLUTTER
# ----------------------------------------------------------------------
flutter:
  uses-material-design: true

  # Liberando a pasta assets para o app usar na tela
  assets:
    - assets/
# ----------------------------------------------------------------------
# GERADOR AUTOMÁTICO DE ÍCONES (Android, iOS e Web)
# ----------------------------------------------------------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icone.png"
  web:
    generate: true
    image_path: "assets/icone.png"